import type { Metadata } from "next";
import "./globals.scss";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Pokemon Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
